import { promises as fs } from "fs";
import path from "path";
import crypto from "crypto";

// Submissions are appended to a JSON-lines file; uploaded CVs sit next to it.
// No database to install or back up — just copy DATA_DIR.

const DATA_DIR = process.env.DATA_DIR || path.join(process.cwd(), "data");
const LOG_FILE = path.join(DATA_DIR, "submissions.jsonl");
const CV_DIR = path.join(DATA_DIR, "cvs");

export const MAX_CV_BYTES = 5 * 1024 * 1024;
export const CV_TYPES = {
  ".pdf": "application/pdf",
  ".doc": "application/msword",
  ".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
};

export async function saveCv(file) {
  const ext = path.extname(file.name || "").toLowerCase();
  if (!CV_TYPES[ext]) throw new Error("CV must be a PDF, DOC or DOCX file.");
  if (file.size > MAX_CV_BYTES) throw new Error("CV must be 5 MB or smaller.");
  await fs.mkdir(CV_DIR, { recursive: true });
  const stored = `${crypto.randomUUID()}${ext}`;
  await fs.writeFile(path.join(CV_DIR, stored), Buffer.from(await file.arrayBuffer()));
  return stored;
}

export async function addSubmission(entry) {
  await fs.mkdir(DATA_DIR, { recursive: true });
  const record = { id: crypto.randomUUID(), createdAt: new Date().toISOString(), ...entry };
  await fs.appendFile(LOG_FILE, JSON.stringify(record) + "\n");
  return record;
}

export async function listSubmissions() {
  let raw;
  try {
    raw = await fs.readFile(LOG_FILE, "utf8");
  } catch (err) {
    if (err.code === "ENOENT") return [];
    throw err;
  }
  return raw
    .split("\n")
    .filter(Boolean)
    .map((line) => {
      try {
        return JSON.parse(line);
      } catch {
        return null;
      }
    })
    .filter(Boolean)
    .reverse();
}

export async function readCv(id) {
  const entry = (await listSubmissions()).find((s) => s.id === id);
  if (!entry?.cv) return null;
  // Stored names are generated by saveCv, but never trust a path from disk blindly.
  const stored = path.basename(entry.cv.stored);
  const data = await fs.readFile(path.join(CV_DIR, stored));
  const ext = path.extname(stored).toLowerCase();
  return { data, type: CV_TYPES[ext] || "application/octet-stream", filename: entry.cv.original || stored };
}
